# Generated by Django 2.2.7 on 2020-06-29 12:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='document',
            field=models.FileField(null=True, upload_to=''),
        ),
    ]
